---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "../inventory/adhoc/hosts.yaml"
        group_file: "../inventory/adhoc/groups.yaml"
        defaults_file: "../inventory/adhoc/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 50